const mongoose = require("mongoose");

const ids = {
  userId: new mongoose.Types.ObjectId("65f001111111111111111111"),
  courseDataStructuresId: new mongoose.Types.ObjectId(
    "65f002222222222222222221",
  ),
  courseDatabasesId: new mongoose.Types.ObjectId("65f002222222222222222222"),
  quizTreesId: new mongoose.Types.ObjectId("65f003333333333333333331"),
  quizSortingId: new mongoose.Types.ObjectId("65f003333333333333333332"),
  quizNormalizationId: new mongoose.Types.ObjectId("65f003333333333333333333"),
  resultTreesId: new mongoose.Types.ObjectId("65f004444444444444444441"),
  resultSortingId: new mongoose.Types.ObjectId("65f004444444444444444442"),
  resultNormalizationId: new mongoose.Types.ObjectId(
    "65f004444444444444444443",
  ),
};

const mockQuizData = {
  user: {
    _id: ids.userId,
    fullName: "Salma Adel",
    email: "salma.adel@unimate.test",
    university: "Cairo University",
  },
  courses: [
    {
      _id: ids.courseDataStructuresId,
      userId: ids.userId,
      code: "CS 301",
      name: "Data Structures",
      instructor: "Dr. Hany Nabil",
      schedule: "Sun/Tue 10:00 AM",
      credits: "3",
      semester: "Spring 2026",
      outlineText:
        "Trees, AVL balancing, deletion, heaps, sorting algorithms, time complexity analysis.",
      assessments: [
        {
          id: "assess-quiz-1",
          title: "Binary Search Trees Practice",
          type: "quiz",
          score: 85,
          maxScore: 100,
          date: new Date("2026-02-09T14:30:00.000Z"),
          weight: 5,
        },
      ],
    },
    {
      _id: ids.courseDatabasesId,
      userId: ids.userId,
      code: "CS 305",
      name: "Database Systems",
      instructor: "Dr. Reem Hassan",
      schedule: "Mon/Wed 1:00 PM",
      credits: "3",
      semester: "Spring 2026",
      outlineText:
        "Relational algebra, SQL joins, subqueries, normalization, indexing, aggregation.",
      assessments: [
        {
          id: "assess-quiz-2",
          title: "SQL Queries",
          type: "quiz",
          score: 68,
          maxScore: 100,
          date: new Date("2026-02-07T11:00:00.000Z"),
          weight: 5,
        },
      ],
    },
  ],
  quizzes: [
    {
      _id: ids.quizTreesId,
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      title: "Binary Search Trees",
      description:
        "Targeted review on traversal, balancing, and delete operations.",
      generationType: "rag_generated",
      questionTypeFilter: "all",
      difficulty: "mixed",
      totalQuestions: 5,
      estimatedDurationMinutes: 12,
      subTopicCoverage: ["tree-traversal", "avl-balancing", "bst-deletion"],
      recommendedBySystem: false,
      questions: [
        {
          questionId: "bst-q1",
          prompt:
            "Which traversal visits nodes in sorted order for a binary search tree?",
          type: "mcq",
          difficulty: "easy",
          options: [
            { key: "A", text: "Preorder" },
            { key: "B", text: "Inorder" },
            { key: "C", text: "Postorder" },
            { key: "D", text: "Level-order" },
          ],
          correctAnswer: "B",
          explanation: "Inorder traversal yields ascending order in a BST.",
          points: 1,
          estimatedSeconds: 45,
          subTopicTags: ["tree-traversal"],
          sourceChunks: ["week-4-notes#traversals"],
        },
        {
          questionId: "bst-q2",
          prompt:
            "A node in an AVL tree becomes unbalanced after insertion. Which metric determines whether rotation is needed?",
          type: "mcq",
          difficulty: "medium",
          options: [
            { key: "A", text: "Tree diameter" },
            { key: "B", text: "Balance factor" },
            { key: "C", text: "Node color" },
            { key: "D", text: "Branching factor" },
          ],
          correctAnswer: "B",
          explanation:
            "AVL rotations are triggered by the node's balance factor.",
          points: 1,
          estimatedSeconds: 60,
          subTopicTags: ["avl-balancing"],
          sourceChunks: ["week-5-notes#avl"],
        },
        {
          questionId: "bst-q3",
          prompt:
            "Deleting a BST node with two children typically replaces it with which node?",
          type: "mcq",
          difficulty: "medium",
          options: [
            { key: "A", text: "The root" },
            { key: "B", text: "Any leaf node" },
            { key: "C", text: "Its inorder predecessor or successor" },
            { key: "D", text: "Its parent" },
          ],
          correctAnswer: "C",
          explanation:
            "A common strategy is replacing it with the inorder predecessor or successor.",
          points: 1,
          estimatedSeconds: 75,
          subTopicTags: ["bst-deletion"],
          sourceChunks: ["week-4-notes#deletion"],
        },
        {
          questionId: "bst-q4",
          prompt:
            "True or false: A left-right AVL imbalance is fixed by a single right rotation.",
          type: "true_false",
          difficulty: "hard",
          correctAnswer: false,
          explanation:
            "A left-right case needs a left rotation on the child, then a right rotation on the node.",
          points: 1,
          estimatedSeconds: 50,
          subTopicTags: ["avl-balancing"],
          sourceChunks: ["week-5-notes#double-rotations"],
        },
        {
          questionId: "bst-q5",
          prompt: "Name one valid use case for postorder traversal in trees.",
          type: "short_answer",
          difficulty: "medium",
          correctAnswer: "deleting a tree",
          explanation:
            "Postorder is useful when children must be processed before the parent.",
          points: 1,
          estimatedSeconds: 90,
          subTopicTags: ["tree-traversal"],
          sourceChunks: ["week-4-notes#traversals"],
        },
      ],
      sourceContext: {
        materialIds: ["week-4-notes", "week-5-notes"],
        retrievalQuery:
          "Generate a mixed BST and AVL quiz from recent lecture notes",
        generatedAt: new Date("2026-02-08T17:00:00.000Z"),
      },
      createdAt: new Date("2026-02-08T17:00:00.000Z"),
      updatedAt: new Date("2026-02-08T17:00:00.000Z"),
    },
    {
      _id: ids.quizSortingId,
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      title: "Sorting Algorithms Review",
      description: "Short review set on merge sort, quicksort, and heap sort.",
      generationType: "scheduled_review",
      questionTypeFilter: "mcq",
      difficulty: "medium",
      totalQuestions: 10,
      estimatedDurationMinutes: 15,
      subTopicCoverage: ["merge-sort", "quicksort", "heap-sort"],
      recommendedBySystem: true,
      recommendationReason:
        "Recent quicksort mistakes and 6 days since the last review.",
      dueForReviewAt: new Date("2026-03-28T09:00:00.000Z"),
      questions: [],
      sourceContext: {
        materialIds: ["week-6-slides"],
        retrievalQuery:
          "Generate a medium difficulty review on sorting algorithms",
        generatedAt: new Date("2026-03-26T09:00:00.000Z"),
      },
      createdAt: new Date("2026-03-26T09:00:00.000Z"),
      updatedAt: new Date("2026-03-26T09:00:00.000Z"),
    },
    {
      _id: ids.quizNormalizationId,
      userId: ids.userId,
      courseId: ids.courseDatabasesId,
      title: "Database Normalization",
      description:
        "Focused review on functional dependencies and normal forms.",
      generationType: "scheduled_review",
      questionTypeFilter: "all",
      difficulty: "medium",
      totalQuestions: 12,
      estimatedDurationMinutes: 18,
      subTopicCoverage: [
        "functional-dependencies",
        "third-normal-form",
        "bcnf",
      ],
      recommendedBySystem: true,
      recommendationReason:
        "Low score on SQL foundations and overdue database review.",
      dueForReviewAt: new Date("2026-03-27T08:00:00.000Z"),
      questions: [],
      sourceContext: {
        materialIds: ["db-unit-2-notes"],
        retrievalQuery:
          "Generate a follow-up quiz after weak SQL and normalization results",
        generatedAt: new Date("2026-03-25T13:00:00.000Z"),
      },
      createdAt: new Date("2026-03-25T13:00:00.000Z"),
      updatedAt: new Date("2026-03-25T13:00:00.000Z"),
    },
  ],
  quizResults: [
    {
      _id: ids.resultTreesId,
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      quizId: ids.quizTreesId,
      score: 85,
      correctAnswers: 4,
      totalQuestions: 5,
      weakAreas: ["avl-balancing", "bst-deletion"],
      attemptNumber: 1,
      submissionSource: "practice",
      completedAt: new Date("2026-02-09T14:30:00.000Z"),
      answeredQuestions: [
        {
          questionId: "bst-q1",
          prompt:
            "Which traversal visits nodes in sorted order for a binary search tree?",
          subTopicTags: ["tree-traversal"],
          selectedAnswer: "B",
          correctAnswer: "B",
          isCorrect: true,
          pointsEarned: 1,
          maxPoints: 1,
          responseTimeSeconds: 31,
        },
        {
          questionId: "bst-q2",
          prompt:
            "A node in an AVL tree becomes unbalanced after insertion. Which metric determines whether rotation is needed?",
          subTopicTags: ["avl-balancing"],
          selectedAnswer: "D",
          correctAnswer: "B",
          isCorrect: false,
          pointsEarned: 0,
          maxPoints: 1,
          responseTimeSeconds: 74,
        },
        {
          questionId: "bst-q3",
          prompt:
            "Deleting a BST node with two children typically replaces it with which node?",
          subTopicTags: ["bst-deletion"],
          selectedAnswer: "C",
          correctAnswer: "C",
          isCorrect: true,
          pointsEarned: 1,
          maxPoints: 1,
          responseTimeSeconds: 66,
        },
        {
          questionId: "bst-q4",
          prompt:
            "True or false: A left-right AVL imbalance is fixed by a single right rotation.",
          subTopicTags: ["avl-balancing"],
          selectedAnswer: true,
          correctAnswer: false,
          isCorrect: false,
          pointsEarned: 0,
          maxPoints: 1,
          responseTimeSeconds: 52,
        },
        {
          questionId: "bst-q5",
          prompt: "Name one valid use case for postorder traversal in trees.",
          subTopicTags: ["tree-traversal"],
          selectedAnswer: "Deleting a tree after its children",
          correctAnswer: "deleting a tree",
          isCorrect: true,
          pointsEarned: 1,
          maxPoints: 1,
          responseTimeSeconds: 87,
        },
      ],
      spacedRepetition: {
        repetitions: 1,
        intervalDays: 3,
        easeFactor: 2.36,
        nextReviewAt: new Date("2026-02-12T14:30:00.000Z"),
        lastQualityScore: 4,
      },
      createdAt: new Date("2026-02-09T14:30:00.000Z"),
      updatedAt: new Date("2026-02-09T14:30:00.000Z"),
    },
    {
      _id: ids.resultSortingId,
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      quizId: ids.quizSortingId,
      score: 74,
      correctAnswers: 7,
      totalQuestions: 10,
      weakAreas: ["quicksort", "heap-sort"],
      attemptNumber: 1,
      submissionSource: "review",
      completedAt: new Date("2026-03-21T09:10:00.000Z"),
      answeredQuestions: [
        {
          questionId: "sort-q3",
          prompt:
            "Which partition strategy is commonly associated with quicksort?",
          subTopicTags: ["quicksort"],
          selectedAnswer: "Merge partition",
          correctAnswer: "Lomuto or Hoare partition",
          isCorrect: false,
          pointsEarned: 0,
          maxPoints: 1,
          responseTimeSeconds: 61,
        },
      ],
      spacedRepetition: {
        repetitions: 0,
        intervalDays: 1,
        easeFactor: 2.1,
        nextReviewAt: new Date("2026-03-28T09:10:00.000Z"),
        lastQualityScore: 2,
      },
      createdAt: new Date("2026-03-21T09:10:00.000Z"),
      updatedAt: new Date("2026-03-21T09:10:00.000Z"),
    },
    {
      _id: ids.resultNormalizationId,
      userId: ids.userId,
      courseId: ids.courseDatabasesId,
      quizId: ids.quizNormalizationId,
      score: 68,
      correctAnswers: 8,
      totalQuestions: 12,
      weakAreas: ["joins", "subqueries", "aggregation"],
      attemptNumber: 1,
      submissionSource: "practice",
      completedAt: new Date("2026-02-07T11:00:00.000Z"),
      answeredQuestions: [
        {
          questionId: "sql-q4",
          prompt: "Which join returns only matching rows from both tables?",
          subTopicTags: ["joins"],
          selectedAnswer: "LEFT JOIN",
          correctAnswer: "INNER JOIN",
          isCorrect: false,
          pointsEarned: 0,
          maxPoints: 1,
          responseTimeSeconds: 42,
        },
        {
          questionId: "sql-q7",
          prompt: "A subquery used in a WHERE clause usually returns what?",
          subTopicTags: ["subqueries"],
          selectedAnswer: "A table alias",
          correctAnswer: "A scalar value or set depending on the operator",
          isCorrect: false,
          pointsEarned: 0,
          maxPoints: 1,
          responseTimeSeconds: 78,
        },
        {
          questionId: "sql-q9",
          prompt: "Which clause is used to filter grouped results?",
          subTopicTags: ["aggregation"],
          selectedAnswer: "WHERE",
          correctAnswer: "HAVING",
          isCorrect: false,
          pointsEarned: 0,
          maxPoints: 1,
          responseTimeSeconds: 39,
        },
      ],
      spacedRepetition: {
        repetitions: 0,
        intervalDays: 1,
        easeFactor: 1.9,
        nextReviewAt: new Date("2026-03-27T08:00:00.000Z"),
        lastQualityScore: 1,
      },
      createdAt: new Date("2026-02-07T11:00:00.000Z"),
      updatedAt: new Date("2026-02-07T11:00:00.000Z"),
    },
  ],
  topicMastery: [
    {
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      tag: "tree-traversal",
      masteryScore: 82,
      confidence: 0.76,
      attempts: 2,
      correctAttempts: 2,
      incorrectAttempts: 0,
      lastSeenAt: new Date("2026-02-09T14:30:00.000Z"),
      lastMasteredAt: new Date("2026-02-09T14:30:00.000Z"),
      lastQuizResultId: ids.resultTreesId,
      needsReview: false,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      tag: "avl-balancing",
      masteryScore: 46,
      confidence: 0.72,
      attempts: 2,
      correctAttempts: 0,
      incorrectAttempts: 2,
      lastSeenAt: new Date("2026-02-09T14:30:00.000Z"),
      lastQuizResultId: ids.resultTreesId,
      needsReview: true,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      tag: "bst-deletion",
      masteryScore: 58,
      confidence: 0.51,
      attempts: 1,
      correctAttempts: 1,
      incorrectAttempts: 0,
      lastSeenAt: new Date("2026-02-09T14:30:00.000Z"),
      lastQuizResultId: ids.resultTreesId,
      needsReview: true,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      tag: "quicksort",
      masteryScore: 49,
      confidence: 0.48,
      attempts: 3,
      correctAttempts: 1,
      incorrectAttempts: 2,
      lastSeenAt: new Date("2026-03-21T09:10:00.000Z"),
      lastQuizResultId: ids.resultSortingId,
      needsReview: true,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDataStructuresId,
      tag: "heap-sort",
      masteryScore: 55,
      confidence: 0.44,
      attempts: 2,
      correctAttempts: 1,
      incorrectAttempts: 1,
      lastSeenAt: new Date("2026-03-21T09:10:00.000Z"),
      lastQuizResultId: ids.resultSortingId,
      needsReview: true,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDatabasesId,
      tag: "joins",
      masteryScore: 40,
      confidence: 0.68,
      attempts: 3,
      correctAttempts: 1,
      incorrectAttempts: 2,
      lastSeenAt: new Date("2026-02-07T11:00:00.000Z"),
      lastQuizResultId: ids.resultNormalizationId,
      needsReview: true,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDatabasesId,
      tag: "subqueries",
      masteryScore: 38,
      confidence: 0.64,
      attempts: 2,
      correctAttempts: 0,
      incorrectAttempts: 2,
      lastSeenAt: new Date("2026-02-07T11:00:00.000Z"),
      lastQuizResultId: ids.resultNormalizationId,
      needsReview: true,
    },
    {
      userId: ids.userId,
      courseId: ids.courseDatabasesId,
      tag: "aggregation",
      masteryScore: 43,
      confidence: 0.59,
      attempts: 2,
      correctAttempts: 0,
      incorrectAttempts: 2,
      lastSeenAt: new Date("2026-02-07T11:00:00.000Z"),
      lastQuizResultId: ids.resultNormalizationId,
      needsReview: true,
    },
  ],
};

module.exports = {
  ids,
  mockQuizData,
};
